-- aimccoy

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Makers;
DROP TABLE IF EXISTS Names;
DROP TABLE IF EXISTS Data;
DROP TABLE IF EXISTS Continents;
DROP TABLE IF EXISTS Countries;
DROP TABLE IF EXISTS Models;
SET FOREIGN_KEY_CHECKS = 1;
